baseURL = "https://tarragonaguide.tinuriel.workers.dev/"
title = "Tarraco Guide"
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[languages]
  [languages.ru]
    weight = 1
    label = "RU"
    locale = "ru-RU"
    title = "Таррагона · гид"
  [languages.uk]
    weight = 2
    label = "UA"
    locale = "uk-UA"
    title = "Таррагона · гід"
  [languages.en]
    weight = 3
    label = "EN"
    locale = "en-GB"
    title = "Tarragona · guide"
  [languages.es]
    weight = 4
    label = "ES"
    locale = "es-ES"
    title = "Tarragona · guía"
  [languages.ca]
    weight = 5
    label = "CA"
    locale = "ca-ES"
    title = "Tarragona · guia"

[imaging]
  resampleFilter = "Lanczos"
  [imaging.webp]
    quality = 78
  [imaging.jpeg]
    quality = 80

[markup.goldmark.renderer]
  unsafe = true
